name: tests

on:
  - push

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Run tests
        run: .github/scripts/run_tests.sh
